language: node_js
sudo: false

node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "node"

env:
  TASK: test

matrix:
  include:
    - node_js: "10"
      env:
        TASK: lint
  allow_failures:
    - node_js: "node"

before_script:
  - export HARMONY_OPTS=$(node --v8-options | grep --only-matching -- '--harmony_generators')

script:
  - npm run $TASK

after_script:
  - npm run coveralls
